# Generated by Django 4.1 on 2022-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.AddField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации на сайте'),
        ),
    ]
